name: 错误反馈 / Bug report
title: "[BUG] "
description: 反馈你遇到的错误 / Report the bug you encountered
labels: ["pending triage"]

body:
  - type: markdown
    attributes:
      value: |
        ## 感谢您花时间填写, 在提交问题之前, 请确保您完成以下操作
        1. 请 **确保** 您已经查阅了 [GKD 官方文档](https://gkd.li)  以及 [常见问题](https://gkd.li/guide/faq)
        2. 请 **判断** 是不是第三方规则订阅的问题, 如果是, 你应该向规则提供者反馈, 而不是在这里提交
        3. 请 **确保** 已有的 [问题](https://github.com/gkd-kit/gkd/issues?q=is%3Aissue) 或 [讨论](https://github.com/orgs/gkd-kit/discussions?discussions_q=) 中没有人提交过相似问题，否则请在该问题下进行讨论
        4. 请 **不要** 开启重复相关的 issue，这将导致别人搜索 issue 时出现无关的低质量信息, 否则你的问题将会被直接关闭甚至删除
        5. 请 **确保** 你的问题能在 [releases](https://github.com/gkd-kit/gkd/releases/latest) 发布的最新版本(包含测试版本)上复现 (如果不是请先更新到最新版本复现后再提交问题)
        6. 请 **务必** 给issue填写一个简洁明了的标题，以便他人快速检索
  - type: textarea
    id: log-file
    attributes:
      label: |
        日志文件
      description: |
        主页-设置-高级设置-日志, 上传日志文件或生成链接并粘贴到下面的输入框\
        任何问题都需要提供日志文件. 否则将直接关闭, 请不要纯发文字/截图/视频
    validations:
      required: true
  - type: textarea
    id: bug-1
    attributes:
      label: |
        BUG描述(文字/截图/视频)
      description: |
        请使用尽量准确的描述, 否则你的问题将会被直接关闭\
        另外如果你的问题是关于快照/选择器的, 请必须提供快照链接或者快照文件, 否则你的问题将会被直接关闭
    validations:
      required: true
  - type: textarea
    id: bug-2
    attributes:
      label: |
        期望行为(文字/截图/视频)
      description: |
        请使用尽量准确的描述, 否则你的问题将会被直接关闭
    validations:
      required: true
  - type: textarea
    id: bug-3
    attributes:
      label: |
        实际行为(文字/截图/视频)
      description: |
        请使用尽量准确的描述, 否则你的问题将会被直接关闭
    validations:
      required: true
